server:
  port: 9192

spring:  application:    name: CONFIG-SERVER
  cloud:    config:      server:        git:          uri: https://github.com/naveenj7/config-server
          clone-on-start: true
