server:
  port: 8989
  
spring:
  application:
    name: GATEWAY-SERVICE
  cloud:    gateway:      routes:      - id: order-service
        uri: lb://ORDER-SERVICE
        predicates:
          - Path=/orders/**
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: ORDER-SERVICE
#              fallbackuri: forward:/orderFallBack      - id: payment-service
        uri: lb://PAYMENT-SERVICE
        predicates:
          - Path=/payment/**  
#        filters:
#          - name: CircuitBreaker
#            args:
#              name: PAYMENT-SERVICE
#              fallbackuri: forward:/paymentFallBack 
    

#hystrix:
#  command:
#    fallbackcmd:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 10000


 
#management:#  endpoints:#    web:#      exposure:#        include: hystrix.stream
 
     
      
       